// <auto-generated />
namespace imdb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatelike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatelike));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131457441_update like "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
