// <auto-generated />
namespace imdb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class d451 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d451));
        
        string IMigrationMetadata.Id
        {
            get { return "202205110459339_d451"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
