// <auto-generated />
namespace imdb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class j89 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(j89));
        
        string IMigrationMetadata.Id
        {
            get { return "202205121019009_j89"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
